doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '14'
        types:
            geometry:   LongitudeOne\Spatial\DBAL\Types\GeometryType
            point:      LongitudeOne\Spatial\DBAL\Types\Geometry\PointType
            polygon:    LongitudeOne\Spatial\DBAL\Types\Geometry\PolygonType
            linestring: LongitudeOne\Spatial\DBAL\Types\Geometry\LineStringType
    orm:
        auto_generate_proxy_classes: false
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine'
                prefix: 'App\Entity'
                alias: App
        dql:
            datetime_functions:
                date_part:          App\DQL\DatePart
            numeric_functions:
                #pow:                App\DQL\Pow
                #round:              App\DQL\Round
                st_point:           LongitudeOne\Spatial\ORM\Query\AST\Functions\Standard\StPoint
                st_x:               LongitudeOne\Spatial\ORM\Query\AST\Functions\Standard\StX
                st_y:               LongitudeOne\Spatial\ORM\Query\AST\Functions\Standard\StY
                st_asgeojson:       LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\SpAsGeoJson
                st_astext:          LongitudeOne\Spatial\ORM\Query\AST\Functions\Standard\StAsText
                st_contains:        LongitudeOne\Spatial\ORM\Query\AST\Functions\Standard\StContains
                st_difference:      LongitudeOne\Spatial\ORM\Query\AST\Functions\Standard\StDifference
                st_distance:        LongitudeOne\Spatial\ORM\Query\AST\Functions\Standard\StDistance
                st_closestpoint:    LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\SpClosestPoint
                st_dwithin:         LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\SpDWithin
                st_startpoint:      LongitudeOne\Spatial\ORM\Query\AST\Functions\Standard\StStartPoint
                st_endpoint:        LongitudeOne\Spatial\ORM\Query\AST\Functions\Standard\StEndPoint
                st_boundary:        LongitudeOne\Spatial\ORM\Query\AST\Functions\Standard\StBoundary
                st_area:            LongitudeOne\Spatial\ORM\Query\AST\Functions\Standard\StArea
                st_length:          LongitudeOne\Spatial\ORM\Query\AST\Functions\Standard\StLength
                st_buffer:          LongitudeOne\Spatial\ORM\Query\AST\Functions\Standard\StBuffer
                st_geomfromtext:    LongitudeOne\Spatial\ORM\Query\AST\Functions\Standard\StGeomFromText
                st_line_interpolate_point:     LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\SpLineInterpolatePoint
                st_line_locate_point:          LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\SpLineLocatePoint
                st_line_substring:  LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\SpLineSubstring
                st_azimuth:         LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\STAzimuth
                st_touches:         LongitudeOne\Spatial\ORM\Query\AST\Functions\Standard\StTouches
                st_crosses:         LongitudeOne\Spatial\ORM\Query\AST\Functions\Standard\StCrosses
                st_intersects:      LongitudeOne\Spatial\ORM\Query\AST\Functions\Standard\StIntersects
                st_intersection:    LongitudeOne\Spatial\ORM\Query\AST\Functions\Standard\StIntersection
                st_makebox2d:       LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\SpMakeBox2D
                st_makeline:        LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\SpMakeLine
                st_extent:          App\ORM\Query\AST\Functions\PostgreSql\SpExtent
                st_scale:           LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\SpScale
                st_union:           LongitudeOne\Spatial\ORM\Query\AST\Functions\Standard\StUnion
                st_split:           LongitudeOne\Spatial\ORM\Query\AST\Functions\PostgreSql\SpSplit
                st_geometryn:       LongitudeOne\Spatial\ORM\Query\AST\Functions\Standard\StGeometryN

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
